import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Three content areas, each an autogenerated sidebar:
 *  - case-studies/  grounded portfolio case studies
 *  - samples/       an invented-but-realistic mini documentation set
 *  - meta/          the self-referential case study of this site
 */
const sidebars: SidebarsConfig = {
  caseStudiesSidebar: [{type: 'autogenerated', dirName: 'case-studies'}],
  samplesSidebar: [{type: 'autogenerated', dirName: 'samples'}],
  metaSidebar: [{type: 'autogenerated', dirName: 'meta'}],
};

export default sidebars;
